name: votesmartk4
description: "Aplikasi e-Voting SMKN 4 Bogor"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  # 💡 Diperbarui ke versi 8.x.x agar mendukung Gradle & Java terbaru di Flutter Anda
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/